### ISSUE TITLE
Replace empty space with underscore in two file names in record http://opendata.cern.ch/record/545

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#1299] opened 2017-07-20 12:53 UTC
Rename the two files with empty space:

Dimuon SingleMu.csv -> Dimuon_SingleMu.csv
Dimuon DoubleMu.csv -> Dimuon_DoubleMu.csv

The empty space is not accepted in the file name e.g. in pandas.read_csv('file.csv')

**Comment by ArtemisLav** [comment] 2017-12-12 13:47
This has been fixed for COD3, so I'm closing.

**Comment by katilp** [comment] 2017-12-12 15:44
@ArtemisLav  Something has went wrong there in the new record, now there are two file with same name Dimuon.csv, should be Dimuon_SingleMu.csv (for the smaller) and Dimuon_DoubleMu.csv (for the larger)

**Comment by ArtemisLav** [comment] 2017-12-12 15:54
The record is fine; I think the issue is that they have the same name in EOS. If you look at the path, it is clear which file is which:
`root://eospublic.cern.ch//eos/opendata/cms/Run2011A/SingleMu/CSV/12Oct2013-v1/Dimuon.csv`
`root://eospublic.cern.ch//eos/opendata/cms/Run2011A/DoubleMu/CSV/12Oct2013-v1/Dimuon.csv`

On the UI however, it's not obvious, you're right, it looks as though they are the same

**Comment by katilp** [comment] 2017-12-14 08:19
@tiborsimko Could you have a look? The files must appear with different names in this record. I would need this in order to test the new education material, this may break the instructions and I have to know the names in order to correct them in the notebooks

**Comment by katilp** [comment] 2017-12-14 08:23
Changes needed for example in the online notebook which is linked to the CMS release announcement, so this is critical...

**Comment by tiborsimko** [comment] 2017-12-15 10:13
Files renamed on EOS, PR coming..

**Closed** 2017-12-15 10:20 UTC
Labels: Experiment: CMS, Size: easy, Status: in review, Topic: records
