### ISSUE TITLE
Search: text in title

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3641] opened 2024-05-16 16:02 UTC
I'm updating our tutorial for the upcoming CMS OD workshop and I could not find in [the instructions](https://opendata.cern.ch/docs/cod-search-tips) how to do the basic search that the CMS OD users would need:

From [the collision data selection](https://opendata.cern.ch/search?q=&f=type%3ADataset%2Bsubtype%3ACollision&f=experiment%3ACMS&f=year%3A2016&l=list&order=desc&p=1&s=10&sort=mostrecent)
we would like to show how to find datasets with e.g. Muon or Mu in the title
 - -> [Muon](https://opendata.cern.ch/search?q=Muon&f=type%3ADataset%2Bsubtype%3ACollision&f=experiment%3ACMS&f=year%3A2016&l=list&order=asc&p=1&s=10&sort=bestmatch) returns all
  - -> [title:Muon](https://opendata.cern.ch/search?q=title%3AMuon&f=type%3ADataset%2Bsubtype%3ACollision&f=experiment%3ACMS&f=year%3A2016&l=list&order=asc&p=1&s=10&sort=bestmatch) returns empty

Is there a way to do this?

**Comment by psaiz** [comment] 2024-05-17 07:27
Hi Kati, 
Thanks for the message. Would something like [title.tokens:*muon*](https://opendata.cern.ch/search?q=title.tokens%3A%2Amuon%2A&f=type%3ADataset%2Bsubtype%3ACollision&f=experiment%3ACMS&f=year%3A2016&l=list&order=asc&p=1&s=10&sort=bestmatch) work for you?  Note that I've put the `*` before and after `Muon`, since the records have words like `DoubleMuon` or `MuonEG`.

**Comment by katilp** [comment] 2024-05-17 07:35
Perfect, thanks! Can you add that to the search tips?

It would be good to have the tips e.g. from here:

![image](https://github.com/cernopendata/opendata.cern.ch/assets/5859918/0f88e0f3-b80a-4abb-a77e-0ff1a1d4bc00)


I.e. **Help** could be a drop-down menu with a link to the forum and to the search tips.

**Comment by psaiz** [comment] 2024-05-17 08:11
Yes, sure. Good point.

**Comment by psaiz** [comment] 2024-05-23 06:25
What do you think about this?

<img width="1728" alt="Screenshot 2024-05-23 at 08 23 32" src="https://github.com/cernopendata/opendata.cern.ch/assets/12909623/e2017b5e-d33b-4d68-967f-bec68862c617">

And it points to [this entry](https://opendata.cern.ch/docs/cod-search-tips). We could add the example of the title to the document, since the syntax for `title` is a bit special.

**Comment by katilp** [comment] 2024-05-23 07:28
Looks good to me, thanks! It could be "Discussion forum" and "Search tips".
The latter reflects the name of the page.

**Comment by psaiz** [comment] 2024-05-23 16:12
Reopening, since it was closed automatically when this thing got merged... We will close it once it is deployed in production, and if the issue is gone

**Comment by psaiz** [comment] 2024-11-19 08:38
This has been deployed already. Closing the ticket

**Closed by psaiz** 2024-11-19 08:38 UTC
Labels: Topic: search
