### ISSUE TITLE
In IE 11 the event display does not allow loading the files

### ISSUE THREAD

**Issue by suenjedt** [cernopendata/opendata.cern.ch#897] opened 2016-02-01 11:16 UTC
http://opendata.cern.ch/visualise/events/CMS

**Comment by tpmccauley** [comment] 2016-02-01 11:24
@suenjedt what happens instead? Does it just hang there? I just tried it and it seems to work for me (see attached).
<img width="1365" alt="screen shot 2016-02-01 at 11 21 08 am" src="https://cloud.githubusercontent.com/assets/496503/12716123/47eb6a18-c8d6-11e5-85ca-e1270e89b3a5.png">

**Comment by tpmccauley** [comment] 2016-02-01 11:28
@suenjedt In either case, it probably doesn't matter for the display in the currently-deployed version of the portal since that display has been replaced:
<img width="1365" alt="screen shot 2016-02-01 at 11 22 14 am" src="https://cloud.githubusercontent.com/assets/496503/12716256/edf3a448-c8d6-11e5-9e28-c2a6a4a8e955.png">

**Comment by tpmccauley** [comment] 2016-02-01 11:30
@suenjedt then the question is: does the new version work for you or do you have the same problem? :)

**Comment by katilp** [comment] 2016-02-01 13:02
@tpmccauley This was at S'cool lab, with the lab notebooks running on windows 8. They remained "loading" and nothing happened, and it was OK on firefox on these same laptops. We did not try the new version on those computers. I can confirm that it works on my windows 10 with MS Egde 25...

**Comment by tpmccauley** [comment] 2016-02-01 13:24
Hopefully this won't be a problem with the new version of the display, but with the older one running on IE in that environment would it be possible to get some output from the JavaScript console?

**Comment by tpmccauley** [comment] 2016-03-15 14:26
I would close this for the following reasons:
- It was with the older display which has since been replaced
- I was able to use the new display with IE11
- I was also able to use the older display with IE11 and was not able to replicate the problem

**Comment by tiborsimko** [comment] 2016-03-18 13:08
LGTM. @suenjedt  please reopen if necessary.

**Closed by tiborsimko** 2016-03-18 13:08 UTC
Labels: tools, UI
