### ISSUE TITLE
CMS: event display, events do not load

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2268] opened 2018-01-26 12:07 UTC
Event loading is not working in http://opendata.cern.ch/visualise/events/cms:

When clicking on dataset from the file menu on the pop-up window, text "Loading events" displays but nothing happens.

(Chrome and firefox on Windows 10)

**Comment by tiborsimko** [comment] 2018-01-26 12:23
There was a general trouble with EOS file connectivity.  The problem is fixed now.

**Closed by tiborsimko** 2018-01-26 12:23 UTC
Labels: Experiment: CMS, Topic: operations
