### ISSUE TITLE
backend: integrate custom modules

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2921] opened 2020-11-26 14:50 UTC
CERN Open Data uses a few customised modules:

```console
$ cat requirements-production-local-forks.txt
git+https://github.com/lepture/mistune-contrib.git#egg=mistune-contrib
git+https://github.com/pamfilos/invenio-files-rest.git@eos-storage#egg=invenio-files-rest
git+https://github.com/pamfilos/invenio-xrootd.git@eos-storage#egg=invenio-xrootd
```

The changes to `i-f-rest` and `i-xrootd` were required due to special storage of open data files on EOSPUBLIC.

Investigate necessary changes as part of migrating to latest Invenio packages.

This will require adaptations and either hosting customised modules in the `cernopendata` organisation, or, ideally, contributing changes "upstream" so that Invenio packages could be used as is.

**Comment by psaiz** [comment] 2023-12-06 13:50
For filte-rest and xrootd, the difference seems to be the parameter of `create_dir`, which in pamfilos version it is passed as an object attribute of `PyFSFileStorage`, instead of using the argument in the function of `_get_fs`. It would be nice to know the idea behind that change. 

I'd say that the way forward here is to check if the xrootd access works on the opendata-dev instance. It might be better to revisit this one once https://github.com/cernopendata/opendata.cern.ch/issues/3035 has been addressed

**Comment by psaiz** [comment] 2023-12-12 14:20
This is easy to reproduce:
```
>>> import invenio_xrootd
>>> invenio_xrootd.__version__
'2.0.0a2'
>>> uri="root://eospublic.cern.ch//eos/opendata/cms/himc/pAWinter13DR53X/inclBtoJPsiMuMu_5TeV02/GEN-SIM-RECO/pa_2nd_run_STARTHI53_V27-v1/file-indexes/CMS_himc_pAWinter13DR53X_inclBtoJPsiMuMu_5TeV02_GEN-SIM-RECO_pa_2nd_run_STARTHI53_V27-v1_50000_file_index.txt"
>>> invenio_xrootd.XRootDFileStorage(uri).open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/xrootd/invenio_files_rest/storage/pyfs.py", line 55, in open
    fs, path = self._get_fs()
  File "/tmp/xrootd/invenio_xrootd/storage.py", line 56, in _get_fs
    fs.makedir("", recursive=True, allow_recreate=True)
  File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/xrootdpyfs/fs.py", line 359, in makedir
    self._raise_status(path, status)
  File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/xrootdpyfs/fs.py", line 163, in _raise_status
    raise ResourceError(path=path, msg=status)
fs.errors.ResourceError: <exception str() failed>
>>> 
```
With the patches from pamfilos, it works. I'll check with our colleagues how to incorporate this.

**Comment by psaiz** [comment] 2023-12-12 14:55
https://github.com/inveniosoftware/invenio-files-rest/pull/302

**Comment by psaiz** [comment] 2023-12-14 10:41
That one has been merged and released

**Closed by psaiz** 2023-12-14 10:41 UTC
