### ISSUE TITLE
installation: fix fixtures cli crash

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1520] opened 2017-10-16 16:38 UTC
The COD3 installation now fails to install fixtures with:

```console
$ docker-compose run --rm web ./scripts/populate-instance.sh
[...]
Traceback (most recent call last):
  File "/usr/local/var/cernopendata/bin/cernopendata", line 11, in <module>
    load_entry_point('cernopendata', 'console_scripts', 'cernopendata')()
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/code/cernopendata/modules/fixtures/cli.py", line 112, in glossary_terms
    record = Record.create(data, id_=id)
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/invenio_records/api.py", line 192, in create
    record=record
  File "/usr/local/var/cernopendata/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
TypeError: __call__() got multiple values for keyword argument 'record'
```
@annatrz @ioannistsanaktsidis @pamfilos are you seeing the same?

**Comment by ioannistsanaktsidis** [comment] 2017-10-17 09:20
@tiborsimko  I can not reproduce the problem :/ From your traceback I see that the problem is in glossary, but for me they are added without any issue.

**Comment by tiborsimko** [comment] 2017-10-17 09:33
@ioannistsanaktsidis Are you using the latest versions of packages, notably `invenio-records` mentioned in the traceback? I have:

```console
$ pip freeze  | grep invenio-records
invenio-records==1.0.0b3
invenio-records-files==1.0.0a9
invenio-records-rest==1.0.0b2
invenio-records-ui==1.0.0b1
```

You can try to build COD3 in a new virgin venv to reproduce the problem. (Or reproduce via docker.)

P.S. Note that if we are to deploy COD3 on DEV every night, then we are using the latest versions of all dependencies every day... We could pin dependencies more strictly, but I think it's OK to go for latest releases on the DEV site.)

**Comment by ioannistsanaktsidis** [comment] 2017-10-17 09:38
hmmm thats probably the issue. This is my installation packages 
```
invenio-records==1.0.0b2
invenio-records-files==1.0.0a9
invenio-records-rest==1.0.0b1
invenio-records-ui==1.0.0b1
```

**Comment by tiborsimko** [comment] 2017-10-17 12:15
We may need to pin, see the discussion in https://gitter.im/inveniosoftware today, since the release of the other dependent packages may take a week.  @ioannistsanaktsidis Can you please make a PR pinning all the good versions of packages that you are using?

**Comment by ioannistsanaktsidis** [comment] 2017-10-17 12:26
@tiborsimko yes I will pin them and we can update when everything is merged.

**Closed** 2017-10-17 16:54 UTC
Labels: Lane: fast, Status: in review, Topic: system
