### ISSUE TITLE
xml file download behaviour

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#2139] opened 2017-12-14 12:04 UTC
The download behaviour has changed back to the problematic one, i.e. download gives error for CMS BuildFile.xml because they are not proper xml (if no proper output is chosen by the user, I guess this is browser specific).

It was solved for CODP2 see
http://opendata.cern.ch/record/461 
but has come back CODP3 see
http://opendata-dev.web.cern.ch/record/461

There a 5 files with xml  (easy to find now with the new search 👍 )
http://opendata-dev.web.cern.ch/search?page=1&size=20&q=&file_type=xml
They are all the same type of BuildFile.xml . It was agreed that we can put from our (CMS) side the tag pair <buildfile></buildfile> around the contents and that would help.
Maybe the easiest is to fix these file with these tags, if it solves the problem. Currently I cannot fully test as all xml files are without this tag pair.

**Comment by ioannistsanaktsidis** [comment] 2017-12-18 13:55
@katilp I cannot reproduce the problem :( I am downloading the file both from COD2 and COD3 and I get exactly the same  output.
```
<use name="FWCore/Framework"/>
<use name="FWCore/PluginManager"/>
<use name="FWCore/ParameterSet"/>
<use name="DataFormats/TrackReco"/>
<use name="CommonTools/UtilAlgos"/>
<use name="PhysicsTools/UtilAlgos"/>
<use name="DataFormats/MuonReco"/>
<use name="RecoMuon/TrackingTools"/>
<flags EDM_PLUGIN="1"/>
<export>
   <lib name="1"/>
</export>
```
Am I missing sth ?

**Comment by katilp** [comment] 2017-12-18 14:05
Ok, thanks for checking, I suspect then that it is due to my broswer settings

**Comment by ioannistsanaktsidis** [comment] 2017-12-18 14:15
Ok, perfect! I am closing then the issue as it seems resolved. In case it happens again we can reopen it :) Thanks!

**Closed by ioannistsanaktsidis** 2017-12-18 14:15 UTC
Labels: Experiment: CMS, Topic: files
