### ISSUE TITLE
Links missing in CMS VM tools page

### ISSUE THREAD

**Issue by RaoOfPhysics** [cernopendata/opendata.cern.ch#801] opened 2015-07-15 16:56 UTC
http://opendata.cern.ch/record/250

See under `Validation` and `Issues & Limitations`:

![firefox - cms vm image - cern open data portal - screen shot 15 july 2015 18 55](https://cloud.githubusercontent.com/assets/7623019/8704406/147333d8-2b23-11e5-8329-29b8b4143e38.png)

**Comment by tiborsimko** [comment] 2015-07-15 17:53
- The validation issue is fixed in `master` already (see DEV).   Will appear on PROD after concluding next QA cycle.

- The issues & limitations issue is caused by missing `556__u` in our data model.  We already have an issue for that, see https://github.com/cernopendata/opendata.cern.ch/issues/779.

I'm therefore closing this issue as duplicate.

**Closed by tiborsimko** 2015-07-15 17:53 UTC
Labels: bug, templates

**Comment by RaoOfPhysics** [comment] 2015-07-16 10:31
> I'm therefore closing this issue as duplicate.

:+1: Apologies about not catching this myself.
